// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYps5pH1oXpwqxp9DL4Jobh3Q53P3-Cwg',
    appId: '1:291720696356:android:5da3e49ecddca81af03eb1',
    messagingSenderId: '291720696356',
    projectId: 'fir-4f7e5',
    databaseURL: 'https://fir-4f7e5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4f7e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEjSUQeD6YNiM7EAbFS-1hBS4R88BVO04',
    appId: '1:291720696356:ios:5b4f46520845b91cf03eb1',
    messagingSenderId: '291720696356',
    projectId: 'fir-4f7e5',
    databaseURL: 'https://fir-4f7e5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4f7e5.appspot.com',
    iosClientId: '291720696356-urkkj4rkutd222lap270v798camj9un8.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartinevntary',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBikopHWHvIrDvzUb3MRCk0xUlJzbz4tPM',
    appId: '1:291720696356:web:e08e3eadb378d18df03eb1',
    messagingSenderId: '291720696356',
    projectId: 'fir-4f7e5',
    authDomain: 'fir-4f7e5.firebaseapp.com',
    databaseURL: 'https://fir-4f7e5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4f7e5.appspot.com',
    measurementId: 'G-87RXC2NX48',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEjSUQeD6YNiM7EAbFS-1hBS4R88BVO04',
    appId: '1:291720696356:ios:5b4f46520845b91cf03eb1',
    messagingSenderId: '291720696356',
    projectId: 'fir-4f7e5',
    databaseURL: 'https://fir-4f7e5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4f7e5.appspot.com',
    iosClientId: '291720696356-urkkj4rkutd222lap270v798camj9un8.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartinevntary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBikopHWHvIrDvzUb3MRCk0xUlJzbz4tPM',
    appId: '1:291720696356:web:88d2f7aec924322ef03eb1',
    messagingSenderId: '291720696356',
    projectId: 'fir-4f7e5',
    authDomain: 'fir-4f7e5.firebaseapp.com',
    databaseURL: 'https://fir-4f7e5-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4f7e5.appspot.com',
    measurementId: 'G-BPXYCCZVNH',
  );

}